version: '2'

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./etc/nginx.conf:/etc/nginx/nginx.conf
            - ./log:/var/log/nginx
            - ./html:/usr/share/nginx/html
            - ./etc/certbot/conf:/etc/letsencrypt
    certbot:
        image: certbot/certbot:v1.12.0
        volumes:
            - ./etc/certbot/conf:/etc/letsencrypt
            - ./html:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 240h & wait $${!}; done;'"
